name: Backend dockerization

on: 
  push:
env:
  USERNAME: ${{secrets.DOCKERHUB_USERNAME}} 
  TOKEN: ${{secrets.DOCKERHUB_TOKEN}}
  
jobs:
  push_to_registry:
    name: push docker image to hub
    runs-on: ubuntu-latest
    steps:
      - name: check repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          registry: docker.io
          username: $USERNAME
          password: $TOKEN
          logout: false

      # - name: Build and push
      #   uses: docker/build-push-action@v5
      #   with:
      #     context: backend/
      #     push: true
      #     tags: techverito_be:latest
      
